### ISSUE TITLE
03-14 Scrum Meeting Notes 

### ISSUE THREAD

**Issue by SeanWallach** [SeanWallach/SYSC-4806#23]
Things we need for **Alpha** release: 

**User:**
- creation and login page
- browsing published books ability
- password validation
- add to cart feature
- buy feature

**Owner:**
- Edit book feature
- Add images to books
- password validation

**Documentation**
- keep UML diagrams up to date

**Comment by SeanWallach** [comment]
**What I've done**: started JS implementation, migrated TravisCI to .com, meeting notes
**What I will do**: add to cart/buy feature
**What is blocking me**: currently nothing

**Comment by AjFroster** [comment]
What I've done: Helped with java script implementation of book display, helped with git hub conflict issues.
What I'll do before next meeting: Implement User creation and login + Password validation.
What is blocking me: Nothing currently.

**Comment by EverettSoldaat** [comment]
What I've done:  Added Cart and User objects with JPA
What I will do: Add 'Edit Book' feature and adding images to books
What is blocking me: Nothing rn

**Comment by adybka** [comment]
Done: Create owner and book object, H2 db for owner and book, javascript for book creation, book creation for thymeleaf and backend logic 
What to do: List all books page
