### ISSUE TITLE
03-18 Scrum Meeting notes

### ISSUE THREAD

**Issue by SeanWallach** [SeanWallach/SYSC-4806#28]

**Comment by adybka** [comment]
Going to do: start working on creating postgreSQL database on AWS

**Comment by SeanWallach** [comment]
**What I did**: changed book testing, basic browser page implementation
**What I will do:** continue with browser page implementation
**Blockers**: None

**Comment by AjFroster** [comment]
What I've done: Implement User creation and login + Password validation.
What I'll do before next meeting: Help anyone who needs assistance to finish their tasks before Sunday. Think about methods to register the current user/owner logged on.
What is blocking me: Nothing currently.
